#!/usr/bin/env bash
# bash script to install nginx
sudo apt-get -y update
sudo apt-get -y install nginx
sudo mv /usr/share/nginx/html/index.html /usr/share/nginx/html/index.txt
sudo echo "Hello World" > /usr/share/nginx/html/index.html
sudo service nginx restart
