#!/usr/bin/env bash
# bash script to install nginx
sudo apt-get -y update
sudo apt-get -y install nginx
sudo mv /usr/share/nginx/html/index.html /usr/share/nginx/html/index.txt
sudo echo "Hello World" > /usr/share/nginx/html/index.html
new_string=".rules\n\t\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;\n"
sudo sed -i "s/.rules/$new_string/" /etc/nginx/sites-available/default
sudo service nginx restart
