#!/usr/bin/env bash
# This script is displaying "Best School" 9 times and Hi on 10

count=1

while [ $count -le 10 ]
do
	if [ $count -eq 9 ]; then
		echo -e  "Best School\nHi"
	else
		echo "Best School"
	fi
	count=$((count + 1))

done
