#!/usr/bin/env bash
# Use a for loop to iterate over non-hidden files in the current directory
for file in *; do
    # Check if the file is a regular file (not a directory) and not hidden
    if [ -f "$file" ] && [[ "$file" != .* ]]; then
       
 # Extract the part of the filename after the first dash
       
       	filename=$(basename "$file")
        displayname=$(echo "$filename" | cut -d '-' -f 2-)
        echo "$displayname"
    fi
done
