#!/usr/bin/env bash
# Configure Nginx to run as the nginx user
getent passwd nginx
sudo adduser --system --no-create-home --disabled-login --group nginx
sudo nginx -t
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf

# Configure Nginx to listen on all active IPs on port 8080
sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default
rm -rf /etc/nginx/sites-enabled/ ; ln -s /etc/nginx/sites-available/ /etc/nginx/sites-enabled
chmod 644 /etc/nginx/nginx.conf ; pkill apache2
sudo -u nginx service nginx start
